// Copyright 2016 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated.
#ifndef VULKAN_WRAPPER_H
#define VULKAN_WRAPPER_H

#define VK_NO_PROTOTYPES 1
#include <vulkan/vulkan.h>

// 添加这个定义来确保不会与官方头文件冲突
#ifndef VULKAN_WRAPPER_IMPLEMENTATION
#define VK_DEFINE_EXTERN
#else
#define VK_DEFINE_EXTERN extern
#endif

/* Initialize the Vulkan function pointer variables declared in this header.
 * Returns 0 if vulkan is not available, non-zero if it is available.
 */
int InitVulkan(void);

// VK_core
VK_DEFINE_EXTERN PFN_vkCreateInstance vkCreateInstance;
VK_DEFINE_EXTERN PFN_vkDestroyInstance vkDestroyInstance;
VK_DEFINE_EXTERN PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceImageFormatProperties vkGetPhysicalDeviceImageFormatProperties;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
VK_DEFINE_EXTERN PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
VK_DEFINE_EXTERN PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
VK_DEFINE_EXTERN PFN_vkCreateDevice vkCreateDevice;
VK_DEFINE_EXTERN PFN_vkDestroyDevice vkDestroyDevice;
VK_DEFINE_EXTERN PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties;
VK_DEFINE_EXTERN PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;
VK_DEFINE_EXTERN PFN_vkEnumerateInstanceLayerProperties vkEnumerateInstanceLayerProperties;
VK_DEFINE_EXTERN PFN_vkEnumerateDeviceLayerProperties vkEnumerateDeviceLayerProperties;
VK_DEFINE_EXTERN PFN_vkGetDeviceQueue vkGetDeviceQueue;
VK_DEFINE_EXTERN PFN_vkQueueSubmit vkQueueSubmit;
VK_DEFINE_EXTERN PFN_vkQueueWaitIdle vkQueueWaitIdle;
VK_DEFINE_EXTERN PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
VK_DEFINE_EXTERN PFN_vkAllocateMemory vkAllocateMemory;
VK_DEFINE_EXTERN PFN_vkFreeMemory vkFreeMemory;
VK_DEFINE_EXTERN PFN_vkMapMemory vkMapMemory;
VK_DEFINE_EXTERN PFN_vkUnmapMemory vkUnmapMemory;
VK_DEFINE_EXTERN PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
VK_DEFINE_EXTERN PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
VK_DEFINE_EXTERN PFN_vkGetDeviceMemoryCommitment vkGetDeviceMemoryCommitment;
VK_DEFINE_EXTERN PFN_vkBindBufferMemory vkBindBufferMemory;
VK_DEFINE_EXTERN PFN_vkBindImageMemory vkBindImageMemory;
VK_DEFINE_EXTERN PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
VK_DEFINE_EXTERN PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
VK_DEFINE_EXTERN PFN_vkGetImageSparseMemoryRequirements vkGetImageSparseMemoryRequirements;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceSparseImageFormatProperties vkGetPhysicalDeviceSparseImageFormatProperties;
VK_DEFINE_EXTERN PFN_vkQueueBindSparse vkQueueBindSparse;
VK_DEFINE_EXTERN PFN_vkCreateFence vkCreateFence;
VK_DEFINE_EXTERN PFN_vkDestroyFence vkDestroyFence;
VK_DEFINE_EXTERN PFN_vkResetFences vkResetFences;
VK_DEFINE_EXTERN PFN_vkGetFenceStatus vkGetFenceStatus;
VK_DEFINE_EXTERN PFN_vkWaitForFences vkWaitForFences;
VK_DEFINE_EXTERN PFN_vkCreateSemaphore vkCreateSemaphore;
VK_DEFINE_EXTERN PFN_vkDestroySemaphore vkDestroySemaphore;
VK_DEFINE_EXTERN PFN_vkCreateEvent vkCreateEvent;
VK_DEFINE_EXTERN PFN_vkDestroyEvent vkDestroyEvent;
VK_DEFINE_EXTERN PFN_vkGetEventStatus vkGetEventStatus;
VK_DEFINE_EXTERN PFN_vkSetEvent vkSetEvent;
VK_DEFINE_EXTERN PFN_vkResetEvent vkResetEvent;
VK_DEFINE_EXTERN PFN_vkCreateQueryPool vkCreateQueryPool;
VK_DEFINE_EXTERN PFN_vkDestroyQueryPool vkDestroyQueryPool;
VK_DEFINE_EXTERN PFN_vkGetQueryPoolResults vkGetQueryPoolResults;
VK_DEFINE_EXTERN PFN_vkCreateBuffer vkCreateBuffer;
VK_DEFINE_EXTERN PFN_vkDestroyBuffer vkDestroyBuffer;
VK_DEFINE_EXTERN PFN_vkCreateBufferView vkCreateBufferView;
VK_DEFINE_EXTERN PFN_vkDestroyBufferView vkDestroyBufferView;
VK_DEFINE_EXTERN PFN_vkCreateImage vkCreateImage;
VK_DEFINE_EXTERN PFN_vkDestroyImage vkDestroyImage;
VK_DEFINE_EXTERN PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout;
VK_DEFINE_EXTERN PFN_vkCreateImageView vkCreateImageView;
VK_DEFINE_EXTERN PFN_vkDestroyImageView vkDestroyImageView;
VK_DEFINE_EXTERN PFN_vkCreateShaderModule vkCreateShaderModule;
VK_DEFINE_EXTERN PFN_vkDestroyShaderModule vkDestroyShaderModule;
VK_DEFINE_EXTERN PFN_vkCreatePipelineCache vkCreatePipelineCache;
VK_DEFINE_EXTERN PFN_vkDestroyPipelineCache vkDestroyPipelineCache;
VK_DEFINE_EXTERN PFN_vkGetPipelineCacheData vkGetPipelineCacheData;
VK_DEFINE_EXTERN PFN_vkMergePipelineCaches vkMergePipelineCaches;
VK_DEFINE_EXTERN PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
VK_DEFINE_EXTERN PFN_vkCreateComputePipelines vkCreateComputePipelines;
VK_DEFINE_EXTERN PFN_vkDestroyPipeline vkDestroyPipeline;
VK_DEFINE_EXTERN PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
VK_DEFINE_EXTERN PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
VK_DEFINE_EXTERN PFN_vkCreateSampler vkCreateSampler;
VK_DEFINE_EXTERN PFN_vkDestroySampler vkDestroySampler;
VK_DEFINE_EXTERN PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
VK_DEFINE_EXTERN PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
VK_DEFINE_EXTERN PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
VK_DEFINE_EXTERN PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
VK_DEFINE_EXTERN PFN_vkResetDescriptorPool vkResetDescriptorPool;
VK_DEFINE_EXTERN PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
VK_DEFINE_EXTERN PFN_vkFreeDescriptorSets vkFreeDescriptorSets;
VK_DEFINE_EXTERN PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
VK_DEFINE_EXTERN PFN_vkCreateFramebuffer vkCreateFramebuffer;
VK_DEFINE_EXTERN PFN_vkDestroyFramebuffer vkDestroyFramebuffer;
VK_DEFINE_EXTERN PFN_vkCreateRenderPass vkCreateRenderPass;
VK_DEFINE_EXTERN PFN_vkDestroyRenderPass vkDestroyRenderPass;
VK_DEFINE_EXTERN PFN_vkGetRenderAreaGranularity vkGetRenderAreaGranularity;
VK_DEFINE_EXTERN PFN_vkCreateCommandPool vkCreateCommandPool;
VK_DEFINE_EXTERN PFN_vkDestroyCommandPool vkDestroyCommandPool;
VK_DEFINE_EXTERN PFN_vkResetCommandPool vkResetCommandPool;
VK_DEFINE_EXTERN PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
VK_DEFINE_EXTERN PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
VK_DEFINE_EXTERN PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
VK_DEFINE_EXTERN PFN_vkEndCommandBuffer vkEndCommandBuffer;
VK_DEFINE_EXTERN PFN_vkResetCommandBuffer vkResetCommandBuffer;
VK_DEFINE_EXTERN PFN_vkCmdBindPipeline vkCmdBindPipeline;
VK_DEFINE_EXTERN PFN_vkCmdSetViewport vkCmdSetViewport;
VK_DEFINE_EXTERN PFN_vkCmdSetScissor vkCmdSetScissor;
VK_DEFINE_EXTERN PFN_vkCmdSetLineWidth vkCmdSetLineWidth;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthBias vkCmdSetDepthBias;
VK_DEFINE_EXTERN PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds;
VK_DEFINE_EXTERN PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask;
VK_DEFINE_EXTERN PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask;
VK_DEFINE_EXTERN PFN_vkCmdSetStencilReference vkCmdSetStencilReference;
VK_DEFINE_EXTERN PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
VK_DEFINE_EXTERN PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
VK_DEFINE_EXTERN PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
VK_DEFINE_EXTERN PFN_vkCmdDraw vkCmdDraw;
VK_DEFINE_EXTERN PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
VK_DEFINE_EXTERN PFN_vkCmdDrawIndirect vkCmdDrawIndirect;
VK_DEFINE_EXTERN PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect;
VK_DEFINE_EXTERN PFN_vkCmdDispatch vkCmdDispatch;
VK_DEFINE_EXTERN PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect;
VK_DEFINE_EXTERN PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
VK_DEFINE_EXTERN PFN_vkCmdCopyImage vkCmdCopyImage;
VK_DEFINE_EXTERN PFN_vkCmdBlitImage vkCmdBlitImage;
VK_DEFINE_EXTERN PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
VK_DEFINE_EXTERN PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer;
VK_DEFINE_EXTERN PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer;
VK_DEFINE_EXTERN PFN_vkCmdFillBuffer vkCmdFillBuffer;
VK_DEFINE_EXTERN PFN_vkCmdClearColorImage vkCmdClearColorImage;
VK_DEFINE_EXTERN PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage;
VK_DEFINE_EXTERN PFN_vkCmdClearAttachments vkCmdClearAttachments;
VK_DEFINE_EXTERN PFN_vkCmdResolveImage vkCmdResolveImage;
VK_DEFINE_EXTERN PFN_vkCmdSetEvent vkCmdSetEvent;
VK_DEFINE_EXTERN PFN_vkCmdResetEvent vkCmdResetEvent;
VK_DEFINE_EXTERN PFN_vkCmdWaitEvents vkCmdWaitEvents;
VK_DEFINE_EXTERN PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
VK_DEFINE_EXTERN PFN_vkCmdBeginQuery vkCmdBeginQuery;
VK_DEFINE_EXTERN PFN_vkCmdEndQuery vkCmdEndQuery;
VK_DEFINE_EXTERN PFN_vkCmdResetQueryPool vkCmdResetQueryPool;
VK_DEFINE_EXTERN PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp;
VK_DEFINE_EXTERN PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults;
VK_DEFINE_EXTERN PFN_vkCmdPushConstants vkCmdPushConstants;
VK_DEFINE_EXTERN PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;
VK_DEFINE_EXTERN PFN_vkCmdNextSubpass vkCmdNextSubpass;
VK_DEFINE_EXTERN PFN_vkCmdEndRenderPass vkCmdEndRenderPass;
VK_DEFINE_EXTERN PFN_vkCmdExecuteCommands vkCmdExecuteCommands;

// VK_KHR_surface
VK_DEFINE_EXTERN PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;

// VK_KHR_swapchain
VK_DEFINE_EXTERN PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR;
VK_DEFINE_EXTERN PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR;
VK_DEFINE_EXTERN PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR;
VK_DEFINE_EXTERN PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;
VK_DEFINE_EXTERN PFN_vkQueuePresentKHR vkQueuePresentKHR;

// VK_KHR_display
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceDisplayPropertiesKHR vkGetPhysicalDeviceDisplayPropertiesKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
VK_DEFINE_EXTERN PFN_vkGetDisplayPlaneSupportedDisplaysKHR vkGetDisplayPlaneSupportedDisplaysKHR;
VK_DEFINE_EXTERN PFN_vkGetDisplayModePropertiesKHR vkGetDisplayModePropertiesKHR;
VK_DEFINE_EXTERN PFN_vkCreateDisplayModeKHR vkCreateDisplayModeKHR;
VK_DEFINE_EXTERN PFN_vkGetDisplayPlaneCapabilitiesKHR vkGetDisplayPlaneCapabilitiesKHR;
VK_DEFINE_EXTERN PFN_vkCreateDisplayPlaneSurfaceKHR vkCreateDisplayPlaneSurfaceKHR;

// VK_KHR_display_swapchain
VK_DEFINE_EXTERN PFN_vkCreateSharedSwapchainsKHR vkCreateSharedSwapchainsKHR;

#ifdef VK_USE_PLATFORM_XLIB_KHR
// VK_KHR_xlib_surface
VK_DEFINE_EXTERN PFN_vkCreateXlibSurfaceKHR vkCreateXlibSurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR vkGetPhysicalDeviceXlibPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_XCB_KHR
// VK_KHR_xcb_surface
VK_DEFINE_EXTERN PFN_vkCreateXcbSurfaceKHR vkCreateXcbSurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR vkGetPhysicalDeviceXcbPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_WAYLAND_KHR
// VK_KHR_wayland_surface
VK_DEFINE_EXTERN PFN_vkCreateWaylandSurfaceKHR vkCreateWaylandSurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR vkGetPhysicalDeviceWaylandPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_MIR_KHR
// VK_KHR_mir_surface
VK_DEFINE_EXTERN PFN_vkCreateMirSurfaceKHR vkCreateMirSurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceMirPresentationSupportKHR vkGetPhysicalDeviceMirPresentationSupportKHR;
#endif

#ifdef VK_USE_PLATFORM_ANDROID_KHR
// VK_KHR_android_surface
VK_DEFINE_EXTERN PFN_vkCreateAndroidSurfaceKHR vkCreateAndroidSurfaceKHR;
#endif

#ifdef VK_USE_PLATFORM_WIN32_KHR
// VK_KHR_win32_surface
VK_DEFINE_EXTERN PFN_vkCreateWin32SurfaceKHR vkCreateWin32SurfaceKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR vkGetPhysicalDeviceWin32PresentationSupportKHR;
#endif

#ifdef USE_DEBUG_EXTENTIONS
#include <vulkan/vk_sdk_platform.h>
// VK_EXT_debug_report
VK_DEFINE_EXTERN PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallbackEXT;
VK_DEFINE_EXTERN PFN_vkDestroyDebugReportCallbackEXT vkDestroyDebugReportCallbackEXT;
VK_DEFINE_EXTERN PFN_vkDebugReportMessageEXT vkDebugReportMessageEXT;
#endif

// === 新增扩展 ===

// VK_KHR_timeline_semaphore
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2KHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2KHR;
VK_DEFINE_EXTERN PFN_vkGetSemaphoreCounterValueKHR vkGetSemaphoreCounterValueKHR;
VK_DEFINE_EXTERN PFN_vkWaitSemaphoresKHR vkWaitSemaphoresKHR;
VK_DEFINE_EXTERN PFN_vkSignalSemaphoreKHR vkSignalSemaphoreKHR;

// VK_EXT_conditional_rendering
VK_DEFINE_EXTERN PFN_vkCmdBeginConditionalRenderingEXT vkCmdBeginConditionalRenderingEXT;
VK_DEFINE_EXTERN PFN_vkCmdEndConditionalRenderingEXT vkCmdEndConditionalRenderingEXT;

// VK_EXT_extended_dynamic_state
VK_DEFINE_EXTERN PFN_vkCmdSetCullModeEXT vkCmdSetCullModeEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetFrontFaceEXT vkCmdSetFrontFaceEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetPrimitiveTopologyEXT vkCmdSetPrimitiveTopologyEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetViewportWithCountEXT vkCmdSetViewportWithCountEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetScissorWithCountEXT vkCmdSetScissorWithCountEXT;
VK_DEFINE_EXTERN PFN_vkCmdBindVertexBuffers2EXT vkCmdBindVertexBuffers2EXT;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthTestEnableEXT vkCmdSetDepthTestEnableEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthWriteEnableEXT vkCmdSetDepthWriteEnableEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthCompareOpEXT vkCmdSetDepthCompareOpEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetDepthBoundsTestEnableEXT vkCmdSetDepthBoundsTestEnableEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetStencilTestEnableEXT vkCmdSetStencilTestEnableEXT;
VK_DEFINE_EXTERN PFN_vkCmdSetStencilOpEXT vkCmdSetStencilOpEXT;

// KHR_push_descriptor
VK_DEFINE_EXTERN PFN_vkCmdPushDescriptorSetKHR vkCmdPushDescriptorSetKHR;

// EXT_transform_feedback
VK_DEFINE_EXTERN PFN_vkCmdBindTransformFeedbackBuffersEXT vkCmdBindTransformFeedbackBuffersEXT;
VK_DEFINE_EXTERN PFN_vkCmdBeginTransformFeedbackEXT vkCmdBeginTransformFeedbackEXT;
VK_DEFINE_EXTERN PFN_vkCmdEndTransformFeedbackEXT vkCmdEndTransformFeedbackEXT;
VK_DEFINE_EXTERN PFN_vkCmdBeginQueryIndexedEXT vkCmdBeginQueryIndexedEXT;
VK_DEFINE_EXTERN PFN_vkCmdEndQueryIndexedEXT vkCmdEndQueryIndexedEXT;
VK_DEFINE_EXTERN PFN_vkCmdDrawIndirectByteCountEXT vkCmdDrawIndirectByteCountEXT;

// KHR_draw_indirect_count
VK_DEFINE_EXTERN PFN_vkCmdDrawIndirectCountKHR vkCmdDrawIndirectCountKHR;
VK_DEFINE_EXTERN PFN_vkCmdDrawIndexedIndirectCountKHR vkCmdDrawIndexedIndirectCountKHR;

// EXT_external_memory_host
VK_DEFINE_EXTERN PFN_vkGetMemoryHostPointerPropertiesEXT vkGetMemoryHostPointerPropertiesEXT;

// VK_EXT_blend_operation_advanced
VK_DEFINE_EXTERN PFN_vkCmdSetLogicOpEXT vkCmdSetLogicOpEXT;

// VK_EXT_primitive_topology_list_restart
VK_DEFINE_EXTERN PFN_vkCmdSetPrimitiveRestartEnableEXT vkCmdSetPrimitiveRestartEnableEXT;

// VK_EXT_depth_clip_control
VK_DEFINE_EXTERN PFN_vkCmdSetDepthClipNegativeOneToOneEXT vkCmdSetDepthClipNegativeOneToOneEXT;

// VK_EXT_attachment_feedback_loop_layout
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT vkGetPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT;

// VK_EXT_attachment_feedback_loop_dynamic_state
VK_DEFINE_EXTERN PFN_vkCmdSetAttachmentFeedbackLoopEnableEXT vkCmdSetAttachmentFeedbackLoopEnableEXT;

// 移除不存在的函数指针声明
// VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceRobustness2PropertiesEXT vkGetPhysicalDeviceRobustness2PropertiesEXT;
// VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceShaderFloat16Int8FeaturesKHR vkGetPhysicalDeviceShaderFloat16Int8FeaturesKHR;
// VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceCustomBorderColorPropertiesEXT vkGetPhysicalDeviceCustomBorderColorPropertiesEXT;
// VK_DEFINE_EXTERN PFN_vkGetPhysicalDevicePortabilitySubsetPropertiesKHR vkGetPhysicalDevicePortabilitySubsetPropertiesKHR;
VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceFragmentDensityMapPropertiesEXT vkGetPhysicalDeviceFragmentDensityMapPropertiesEXT;
// VK_DEFINE_EXTERN PFN_vkGetPhysicalDeviceFragmentDensityMap2PropertiesEXT vkGetPhysicalDeviceFragmentDensityMap2PropertiesEXT;

#endif // VULKAN_WRAPPER_H
