name: Android CI Fix

on:
  push:
    branches: [ "1" ]
  pull_request:
    branches: [ "1" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      PROJECT_DIR: src/RyujinxAndroid

    steps:
    # ========== 1. 克隆代码 ==========
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: mipad/Test-ryu
        ref: 1
        path: Test-ryu


    # ========== 3. 配置 Java 和 Android 环境 ==========
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build APK
      working-directory: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}/src/RyujinxAndroid/
      run: |
        chmod +x gradlew
        ./gradlew clean assembleRelease \
          -DllvmToolchainPath=$LLVM_PATH \
          --no-daemon \
          --stacktrace
    # ========== 6. 上传产物 ==========
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk
