name: Android CI Fix

on:
  push:
    branches: [ "1" ]
  pull_request:
    branches: [ "1" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      JAVA_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      PROJECT_DIR: src/RyujinxAndroid

    steps:
    # ========== 1. 克隆代码 ==========
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: mipad/Test-ryu
        ref: 1
        path: Test-ryu
        
    - name: Detect Architecture
      run: |
       echo "当前芯片架构: $(uname -m)"
    # 输出结果：
    # - arm64 → Apple Silicon (M1/M2)
    # - x86_64 → Intel

    # ========== 3. 配置 Java 和 Android 环境 ==========
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Configure build
      working-directory: src/RyujinxAndroid
      run: |
          {
            echo "sdk.dir=$ANDROID_SDK_ROOT"
            echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/25.2.9519653"
            echo "cmake.dir=$ANDROID_SDK_ROOT/cmake/3.22.1"
          } > local.properties
          echo "===== 配置文件内容 ====="
          cat local.properties
          
    - name: Build APK
      working-directory: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}
      run: |
        chmod +x gradlew
        ./gradlew clean assembleRelease \
          -DllvmToolchainPath=$LLVM_PATH \
          --no-daemon \
          --stacktrace
    # ========== 6. 上传产物 ==========
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk
