name: Sync Kenji-NX Master to Branch-10

on:
  push:
    branches: [ "10" ]
  pull_request:
    branches: [ "10" ]
  schedule:
    - cron: '0 0 * * *'  # 每日自动触发
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch-10
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHH_PAT }}
          ref: 10
          fetch-depth: 0

      - name: Add Kenji-NX remote
        run: |
          git remote add kenji https://github.com/Kenji-NX/Kenji-NX.git
          git fetch kenji master

      # 新增步骤：配置 Git 用户身份
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Merge Kenji-NX master
        run: |
          git checkout 10
          git merge kenji/master --allow-unrelated-histories -m "Merge Kenji-NX/master into branch-10"
          git push origin 10
