name: Sync External Repository

on:
  schedule:
   - cron: '0 0 * * *'  
  workflow_dispatch:    
  push:
    branches: [ "10" ]
  pull_request:
    branches: [ "10" ]
  

jobs:
  sync-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch-10
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHH_PAT }}
          ref: 10  # 明确指定分支10
          fetch-depth: 0

      - name: Add external remote
        run: |
          git remote add external https://github.com/Kenji-NX/Kenji-NX.git
          git fetch external

      - name: Merge changes
        run: |
          git fetch origin 10
          git checkout 10
          git merge external/main --allow-unrelated-histories -m "Merge Kenji-NX/main into branch-10"
          git push origin 10

      - name: Push changes
        run: |
          git push origin 10           # 推送到你的分支10
