name: Android CI with .NET 9.0.203

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      should_release:
        description: 'Create GitHub Release'
        type: boolean
        default: false
      upload_artifact:
        description: 'Upload APK as artifact'
        type: boolean
        default: true
      release_tag:
        description: 'Custom release tag'
        type: string
        default: ''
      is_prerelease:
        description: 'Mark as pre-release'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      packages: write
    env:
      PROJECT_DIR: src/RyujinxAndroid
      NDK_VERSION: 26.2.11394342
      DOTNET_VERSION: "9.0.203"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: mipad/Test-ryu
        ref: best
        path: Test-ryu

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true

    - name: Verify .NET Version
      run: dotnet --version

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.NDK_VERSION }}

    - name: Install CMake
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.31.6"

    - name: Build with Gradle
      working-directory: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}
      env:
        CMAKE_C_COMPILER_LAUNCHER: "ccache"
        CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
      run: |
        chmod +x gradlew
        # 显式移除 _JAVA_OPTIONS 环境变量
        unset _JAVA_OPTIONS
        ./gradlew clean assembleRelease --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: ${{ inputs.upload_artifact || github.event_name == 'push' }}
      with:
        name: android-release
        path: ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.should_release }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.release_tag || github.sha }}
        prerelease: ${{ inputs.is_prerelease }}
        files: |
          ${{ github.workspace }}/Test-ryu/${{ env.PROJECT_DIR }}/app/build/outputs/apk/release/*.apk
