name: Android CI 

on:
  push:
    branches: [ "main1" ]
  pull_request:
    branches: [ "main1" ]
  workflow_dispatch:
    inputs:
      should_release:
        description: 'Create GitHub Release'
        type: boolean
        default: false
      upload_artifact:
        description: 'Upload APK as artifact'
        type: boolean
        default: true

jobs:
  build:
    runs-on: macOS-latest
    permissions:
      contents: read
      actions: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: mipad/Test-ryu
        ref: main1
        path: Test-ryu

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android NDK
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.2.11394342"
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.2.11394342" >> $GITHUB_ENV

    - name: Install CMake
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1"

    - name: Build Android
      env:
        ORG_RYUJINX_LLVM_TOOLCHAIN_PATH: ${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/darwin-x86_64
      run: |
        cd ${{ github.workspace }}/Test-ryu/src/RyujinxAndroid
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew "assembleRelease" -Porg.ryujinx.llvm.toolchain.path=$ORG_RYUJINX_LLVM_TOOLCHAIN_PATH

    - name: Check Generated Files
      run: |
        echo "----- APK 路径 -----"
        ls -al ${{ github.workspace }}/Test-ryu/src/RyujinxAndroid/app/build/outputs/apk/release/

        echo "----- libryujinx 动态库路径 -----"
        LIB_PATH="${{ github.workspace }}/Test-ryu/src/RyujinxAndroid/libryujinx/build/bin/LibRyujinx/release_android-arm64"
        if [ -d "$LIB_PATH" ]; then
          cd "$LIB_PATH"
          ls -al
          echo "----- 文件类型验证 -----"
          file *
        else
          echo "警告：动态库路径不存在！"
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ryujinx-main1-${{ github.run_number }}
        path: Test-ryu/src/RyujinxAndroid/app/build/outputs/apk/release/*.apk
        retention-days: 7
