name: Android CI 

on:
  push:
    branches: [ "1" ]
  pull_request:
    branches: [ "1" ]
  workflow_dispatch:
    inputs:
      should_release:
        description: 'Create GitHub Release'
        type: boolean
        default: false
      upload_artifact:
        description: 'Upload APK as artifact'
        type: boolean
        default: true
        
jobs:
  build:
    runs-on: macOS-latest
    permissions:
      contents: read
      actions: write
      packages: write
    steps:      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: mipad/Test-ryu
        ref: 1
        path: Test-ryu
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Install CMake
      run: |
         yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" 

    
    - name: Install LLVM and lld
      run: |
          brew install llvm lld
          # 配置环境变量
          echo "LLVM_PATH=$HOMEBREW_LLVM_PATH" >> $GITHUB_ENV
          echo "PATH=$HOMEBREW_LLVM_PATH/bin:$PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L$HOMEBREW_LLVM_PATH/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$HOMEBREW_LLVM_PATH/include" >> $GITHUB_ENV

      
    - name: Check LLVM Tools
      run: |
          clang --version       # 应指向 Homebrew 的 LLVM
          ld64.lld --version    # 确保 lld 可用
          llvm-objcopy --version
          
    - name: Build Android
      run: |
        cd ${{ github.workspace }}/Test-ryu/src/RyujinxAndroid
        chmod +x ./gradlew
        ./gradlew "assembleRelease"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
          name: ryujinx-main1-${{ github.run_number }}
          path: Test-ryu/src/RyujinxAndroid/app/build/outputs/apk/release/*.apk
          retention-days: 7
