name: ryu-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'select branch to build(default: test)'
        required: false
        default: 'test'
        options:
        - test

jobs:
  ryu_android_build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 18

    - name: Clone repository
      run: |
        git clone --branch ${{ github.event.inputs.branch || 'test' }} https://github.com/mipad/Test-ryu.git test
        cd test
        git submodule update --init --recursive

    - id: version
      name: Get version info
      working-directory: ./test
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        echo "hash=$(git log -1 --pretty=format:%H)" >> $GITHUB_OUTPUT
        echo "short_hash=$(git describe --always --long)" >> $GITHUB_OUTPUT
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Setup Gradle cache
      uses: actions/cache@v4
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ steps.version.outputs.hash }}

    - name: Build APK
      working-directory: ./test/src/RyujinxAndroid
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
        mv app/build/outputs/apk/release/*.apk ${{ github.workspace }}/test-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        name: Ryu ${{ steps.version.outputs.version }}
        tag_name: ryu-${{ steps.version.outputs.date }}
        files: ${{ github.workspace }}/test-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk
