name: ryu-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'select branch to build(default: test)'
        required: false
        default: 'test'
        options:
        - test
        

jobs:
  ryu_android_build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 18

    - name: Download  source code
      run: |
        cd ${{ github.workspace }}
        git clone --branch ${{ github.event.inputs.branch }} https://github.com/mipad/Test-ryu/test.git --recursive
        cd Test-ryu/test
        

    - id: version
      name: Get version
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        cd ${{ github.workspace }}/Test-ryu
        echo "hash=$(git log -1 --pretty=format:%H)" >> $GITHUB_OUTPUT
        echo "short_hash=$(git describe --always --long)" >> $GITHUB_OUTPUT
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-Test-ryu-${{ steps.version.outputs.hash }}
        restore-keys: |
            ${{ runner.os }}-Test-ryu-

    #- name: Prepare environment
    #  run: |
    #    sudo apt-get install -y ninja-build
    #      ln -s /usr/bin/ninja .
    - name: Build Android
      run: |
        cd ${{ github.workspace }}/src/RyujinxAndroid
        chmod +x src/RyujinxAndroid/gradlew
        ./gradlew "assembleRelease"
        # bash gradlew build
        mv $(find app/build/outputs/apk/release/* -type f | grep -E "\.apk$") ${{ github.workspace }}/Test-ryu-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release ryu (Test-ryu)
      uses: softprops/action-gh-release@v2
      with:
        name: ryu ${{ steps.version.outputs.date }}
        tag_name: ryu
        files: ${{ github.workspace }}/Test-ryu-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release ryu ${{ steps.version.outputs.date }}
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.version.outputs.date }}
        tag_name: ${{ steps.version.outputs.date }}
        files: ${{ github.workspace }}/Test-ryu-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk
