name: Android CI with Native Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码（包含子模块）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果原生代码依赖子模块（如第三方库）

      # 2. 设置 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. 安装 Android SDK 和 NDK
      - name: Setup Android SDK
        run: |
          # 接受 SDK 许可协议
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

          # 安装指定版本的 SDK 和 NDK
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"  # NDK 版本需与项目配置一致

          # 设置环境变量
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      # 4. 缓存 Gradle 和 NDK（加速后续构建）
      - name: Cache Gradle and NDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            $ANDROID_SDK_ROOT/ndk  # 可选缓存 NDK
          key: ${{ runner.os }}-gradle-${{ hashFiles('src/RyujinxAndroid/**/*.gradle*', 'src/RyujinxAndroid/gradle.properties') }}

      # 5. 授予 gradlew 执行权限
      - name: Make gradlew executable
        run: chmod +x src/RyujinxAndroid/gradlew

      # 6. 编译项目（进入子目录执行）
      - name: Build Android APK
        working-directory: src/RyujinxAndroid  # 关键：切换到项目根目录
        run: ./gradlew assembleDebug --stacktrace
        env:
          # 如果 CMake 需要自定义参数（可选）
          CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"

      # 7. 上传生成的 APK 作为产物
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ryujinx-debug-apk
          path: src/RyujinxAndroid/app/build/outputs/apk/debug/*.apk
