name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      shouldrelease:
        description: Create release
        type: boolean
      uploadbuild:
        description: Upload build
        type: boolean
      releasetag:
        description: Enter the tag name
        type: string
      releasetype:
        description: Make it prerelease
        type: boolean
      islatest:
        description: Mark as latest
        type: boolean
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Setup Gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ github.sha }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build project
      working-directory: ./src/RyujinxAndroid
      env:
        CMAKE_C_COMPILER_LAUNCHER: "ccache"
        CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'workflow_dispatch' }} || ${{ inputs.uploadbuild }}
      with:
        name: android-build
        path: src/RyujinxAndroid/app/build/outputs/apk/release/*.apk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.shouldrelease }}
      with:
        tag_name: ${{ inputs.releasetag }}
        prerelease: ${{ inputs.releasetype }}
        files: src/RyujinxAndroid/app/build/outputs/apk/release/*.apk
