name: Mirror Repository

on:
  workflow_dispatch:
    inputs:
      android:
        description: 'Trigger Android build'
        required: false
        default: 'true'

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone target repo
      run: |
        git clone --branch test https://github.com/mipad/Test-ryu.git mirror

    - name: Sync workflows
      run: |
        mkdir -p mirror/.github/workflows
        cp -v .github/workflows/*.yml mirror/.github/workflows/

    - name: 提交更改
      working-directory: ./mirror
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .github/workflows
        git commit -m "Sync CI workflows"

    - name: Push changes
      uses: ad-m/github-push-action@v1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: ./mirror
        force: true
